USE online_retail;

-- How many orders have we received?
SELECT COUNT(*) AS total_orders FROM orders;

-- How many orders have we received?
SELECT payment_status, SUM(amount) AS total_amount
FROM payments
GROUP BY payment_status;

-- Q3: Number of orders placed by each customer

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC;

-- Q4: Revenue generated by each product

SELECT
p.product_id,p.product_name,
SUM(oi.quantity*oi.unit_price) AS revenue
  FROM products p
   JOIN order_items oi
 ON p.product_id=oi.product_id 
     GROUP BY p.product_id,p.product_name
ORDER BY revenue DESC;

-- Q5: Revenue by product category

SELECT 
   p.category,
   SUM(oi.quantity*oi.unit_price) AS total_revenue
   FROM products p
   JOIN order_items oi
   on p.product_id=oi.product_id
   GROUP BY p.category
   ORDER BY total_revenue DESC;
   
  -- Q6: On average, how much money is spent per order?
  
  SELECT AVG(order_total) AS average_order_value
  FROM(
  SELECT
       order_id,
       SUM(quantity*unit_price) AS order_total
       FROM order_items
       GROUP BY order_id)
       AS order_totals;
       
     -- Q7:  Which customers have spent more than ₹30,000?
       
SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    SUM(oi.quantity * oi.unit_price) AS total_spent
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
HAVING total_spent > 30000
ORDER BY total_spent DESC;

-- Q8:Which payment method do customers use most often?

SELECT
    payment_method,
    COUNT(*) AS number_of_payments
FROM payments
GROUP BY payment_method
ORDER BY number_of_payments DESC;

-- Q9: Order status breakdown

SELECT
status, 
COUNT(*) AS number_of_orders
FROM orders
GROUP BY status
ORDER BY number_of_orders DESC;

-- Q10: Monthly revenue

SELECT
DATE_FORMAT(o.order_date,'%Y-%m') AS sales_month,
SUM(oi.quantity*oi.unit_price) AS total_revenue
FROM orders o
JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY DATE_FORMAT(o.order_date,'%Y-%m')
ORDER BY sales_month;

-- Q11: Top 3 customers by spending
SELECT
c.customer_id,
c.first_name,
c.last_name,
SUM(oi.quantity*oi.unit_price) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
ORDER BY total_spent DESC
LIMIT 3;













  
  
   