CREATE DATABASE college;

USE college;

CREATE TABLE student (
id INT PRIMARY KEY,
name VARCHAR(50),
age INT NOT NULL
);

INSERT INTO student VALUES(1,"AASTHA",19);
INSERT INTO student Values(2,"DEEPTI",20);

SELECT * FROM student;
SHOW DATABASES;
